function difr;

%----------- global variables ----------------

global axes1 axes2 axes3 axes2b axes3b axes4
global ed1 ed2 ed3 ed4 ed5 ed6
global sl1 txt1
global u s c

%------------- figure snd axes ---------------

fig1=figure('Position',[10,40,950,660]);

axes1=axes('Parent',fig1,'Color',[1,1,1],...
           'Units','point',...
           'FontSize',5,...
           'Position',[370 180 330 300]);
       

axes2b=axes('Parent',fig1,'Color',[1,1,1],...
           'Units','point',...
           'FontSize',5,...
           'Position',[15 15 330 130]); 
axes2=axes('Parent',fig1,'Color',[1,1,1],...
           'Units','point',...
           'FontSize',5,...
           'Position',[15 15 330 130]); 

axes3b=axes('Parent',fig1,'Color',[1,1,1],...
           'Units','point',...
           'FontSize',5,...
           'Position',[370 15 330 130]);        
axes3=axes('Parent',fig1,'Color',[1,1,1],...
           'Units','point',...
           'FontSize',5,...
           'Position',[370 15 330 130]);       

axes4=axes('Parent',fig1,'Color',[1,1,1],...
           'Units','point',...
           'FontSize',5,...
           'Position',[20 160 220 220]);        
         
%------------- edits -------------------------

ed1=uicontrol(fig1,'Style','edit',...
                'BackgroundColor',[1,1,1],...
                'Position',[340 620 100 18],...
                'String','20',...
                'HorizontalAlignment','left',...
                'Callback','');
ed2=uicontrol(fig1,'Style','edit',...
                'BackgroundColor',[1,1,1],...
                'Position',[340 600 100 18],...
                'String','50',...
                'HorizontalAlignment','left',...
                'Callback','');   
ed3=uicontrol(fig1,'Style','edit',...
                'BackgroundColor',[1,1,1],...
                'Position',[340 580 100 18],...
                'String','4',...
                'HorizontalAlignment','left',...
                'Callback','');            
ed4=uicontrol(fig1,'Style','edit',...
                'BackgroundColor',[1,1,1],...
                'Position',[60 600 50 18],...
                'String','-5',...
                'HorizontalAlignment','left',...
                'Callback','');                        
ed5=uicontrol(fig1,'Style','edit',...
                'BackgroundColor',[1,1,1],...
                'Position',[170 600 50 18],...
                'String','20',...
                'HorizontalAlignment','left',...
                'Callback','');    
ed6=uicontrol(fig1,'Style','edit',...
                'BackgroundColor',[1,1,1],...
                'Position',[60 560 50 18],...
                'String','0',...
                'HorizontalAlignment','left',...
                'Callback','marker(2)');                             
            
%-------------- sliders ----------------------

sl1=uicontrol(fig1,'Style','slider',...
              'Position',[10 540 320 18],...    
              'Min',-50,'Max',50,...
              'SliderStep',[0.01 0.01],...
              'Callback','marker(1)');
          
%------------- pushbuttons -------------------         

but1=uicontrol(fig1,'Style','pushbutton',...
                 'Position',[10 620 100 18],...
                 'String','Закрыть',...
                 'Callback','close all');    
but2=uicontrol(fig1,'Style','pushbutton',...
                 'Position',[120 620 100 18],...
                 'String','Demo',...
                 'Callback','difrdemo');  
but2=uicontrol(fig1,'Style','pushbutton',...
                 'Position',[10 580 210 18],...
                 'String','пуск',...
                 'Callback','raschfren');                 
             
%-------------- text fields ------------------

txt1=uicontrol(fig1,'Style','text',...
                'BackgroundColor',get(fig1,'Color'),...
                'Position',[240 620 80 20],...
                'HorizontalAlignment','left',...
                'String','L1=',...
                'FontSize',10);  
txt1=uicontrol(fig1,'Style','text',...
                'BackgroundColor',get(fig1,'Color'),...
                'Position',[240 600 80 20],...
                'HorizontalAlignment','left',...
                'String','L2=',...
                'FontSize',10);         
txt1=uicontrol(fig1,'Style','text',...
                'BackgroundColor',get(fig1,'Color'),...
                'Position',[240 580 90 20],...
                'HorizontalAlignment','left',...
                'String','Длина волны',...
                'FontSize',10);                   
txt1=uicontrol(fig1,'Style','text',...
                'BackgroundColor',get(fig1,'Color'),...
                'Position',[10 600 50 18],...
                'HorizontalAlignment','left',...
                'String','Xmin',...
                'FontSize',10);        
txt1=uicontrol(fig1,'Style','text',...
                'BackgroundColor',get(fig1,'Color'),...
                'Position',[120 600 50 18],...
                'HorizontalAlignment','left',...
                'String','Xmax',...
                'FontSize',10);   
txt1=uicontrol(fig1,'Style','text',...
                'BackgroundColor',get(fig1,'Color'),...
                'Position',[10 560 50 18],...
                'HorizontalAlignment','left',...
                'String','Xo',...
                'FontSize',10);      
txt1=uicontrol(fig1,'Style','text',...
                'BackgroundColor',get(fig1,'Color'),...
                'Position',[10 520 300 18],...
                'HorizontalAlignment','left',...
                'String','',...
                'FontSize',10);    